runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2


handlers:
  - url: .*
    script: auto